### ISSUE TITLE
importDXF (v1.38) fails without a GUI

### ISSUE THREAD

**Issue by swill** [yorikvanhavre/Draft-dxf-importer#6]
I am using FreeCAD using the daily build (v15).

When I try to use importDXF via python directly on a system without X installed I get the following.
``` 
FreeCAD 0.15, Libs: 0.15R4542 (Git)
Traceback (most recent call last):
  File "./custom.py", line 9, in <module>
    import importDXF
  File "/usr/lib/freecad/Mod/Draft/importDXF.py", line 53, in <module>
    draftui = FreeCADGui.draftToolBar
NameError: name 'FreeCADGui' is not defined
```

I changed importDXF.py from:
``` python
gui = FreeCAD.GuiUp
if gui:
    import FreeCADGui
try:
    draftui = FreeCADGui.draftToolBar
except AttributeError:
    draftui = None
```
to:
``` python
gui = FreeCAD.GuiUp
if gui:
    import FreeCADGui
try:
    draftui = FreeCADGui.draftToolBar
except (AttributeError, NameError):
    draftui = None
```

This gets me past this issue...

**Comment by yorikvanhavre** [comment]
Fixed now. Thanks!
